### ISSUE TITLE
migrate to dc.gov

### ISSUE THREAD

**Issue by atrueblood** [DCgov/economic-intelligence#30]

**Comment by cmgiven** [comment]
Is this issue resolved by the open.dc.gov/economic-intelligence URL that is now working? Or is there a custom subdomain that @mattbailey0 is working to obtain?

**Comment by atrueblood** [comment]
Yes it's resolved.

Best,
Andrew

Andrew Trueblood
Chief of Staff
Office of the Deputy Mayor for Planning & Economic Development
Government of the District of Columbia
202.724.7906tel:202.724.7906 | Direct
202.727.6365tel:202.727.6365 | Office
andrew.trueblood@dc.govmailto:andrew.trueblood@dc.gov

http://mayor.dc.govhttp://mayor.dc.gov/

On Jan 4, 2016, at 5:17 PM, Chris Given <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this issue resolved by the open.dc.gov/economic-intelligencehttp://open.dc.gov/economic-intelligence URL that is now working? Or is there a custom subdomain that @mattbailey0https://github.com/mattbailey0 is working to obtain?

—
Reply to this email directly or view it on GitHubhttps://github.com/DCgov/economic-intelligence/issues/30#issuecomment-168828610.

Check out DMPED’s new Real Estate Project Pipelinehttp://dmped.dc.gov/page/real-estate-projects for real time updates on the status of real estate projects located across the District of Columbia.
