### ISSUE TITLE
Navigational items "sliding to the right" on active animation: intended?

### ISSUE THREAD

**Issue by audiodude** [DCgov/economic-intelligence#36]
This animation doesn't seem like what is intended. It is non-standard and distracting. Given that it only happens when the link is actively being clicked (":active"), it may be an interaction between the padding values of the `<li>` items which is used to show the thickened border on hover.

**Comment by mseew** [comment]
The navigation bar's animation is inherited from CFPB's DOCter (https://github.com/cfpb/DOCter), on which the DC Gov Guides Template (https://github.com/DCgov/guides-template/) is based. Feel free to submit a pull request with your suggested changes!

**Comment by audiodude** [comment]
Looks like they've already got an issue open for this: https://github.com/cfpb/DOCter/issues/32

**Comment by audiodude** [comment]
Okay I've submitted a PR for the issue on DOCter. What is the process is to get those changes into DC Gov Guides Template and then into this project (once they're merged of course)?
